language: node_js

node_js:
  - 10

jobs:
  include:
    - stage: release
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn semantic-release